#!/bin/bash

# Verifica se o script está sendo executado com permissões de superusuário
if [[ $(id -u) -ne 0 ]]; then
    echo "Este script precisa ser executado com privilégios de superusuário."
    exit 1
fi

# Caminho para o arquivo de configuração SSH
ssh_config_file="/etc/ssh/sshd_config"

# Faz um backup do arquivo original
backup_file="${ssh_config_file}.bak"
cp "$ssh_config_file" "$backup_file"

# Função para alterar ou adicionar uma configuração no arquivo sshd_config
change_ssh_config() {
    local key="$1"
    local value="$2"
    if grep -q "^$key" "$ssh_config_file"; then
        sed -i "s/^$key.*/$key $value/" "$ssh_config_file"
    else
        echo "$key $value" >> "$ssh_config_file"
    fi
}

# Exemplo de uso da função para alterar configurações (descomente e modifique conforme necessário):
# change_ssh_config "Port" "2222"
change_ssh_config "PermitRootLogin" "yes"

# Reinicia o serviço SSH para aplicar as alterações
systemctl restart ssh

echo "Configurações alteradas com sucesso!"
