#!/bin/bash
sudo apt-get update && sudo apt-get dist-upgrade -y
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install curl -y
sudo apt-get install net-tools -y
sudo apt update && sudo apt full-upgrade && sudo apt autoclean && sudo apt autoremove -y
echo "Instalacao concluida com sucesso!"
